=== Krazick/Krazick.github.io/18XX-Game-Engine-XML/public/XSD/18XX-Corporations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" 
	elementFormDefault="qualified" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Certificate">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="FreeCertificate" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="director" use="optional"/>
      <xs:attribute type="xs:byte" name="percentage" use="optional"/>
      <xs:attribute type="xs:string" name="allowedOwners" use="optional"/>
      <xs:attribute type="xs:byte" name="quantity" use="optional"/>
      <xs:attribute type="xs:short" name="corporationId" use="optional"/>
      <xs:attribute type="xs:byte" name="discountAmount" use="optional"/>
      <xs:attribute type="xs:string" name="canBeBidOn" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Benefit">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="actorType" use="optional"/>
          <xs:attribute type="xs:string" name="class" use="optional"/>
          <xs:attribute type="xs:string" name="extra" use="optional"/>
          <xs:attribute type="xs:string" name="mapCell" use="optional"/>
          <xs:attribute type="xs:byte" name="cost" use="optional"/>
          <xs:attribute type="xs:string" name="passive" use="optional"/>
          <xs:attribute type="xs:string" name="closeOnUse" use="optional"/>
          <xs:attribute type="xs:string" name="sameTurn" use="optional"/>
          <xs:attribute type="xs:short" name="corporationID" use="optional"/>
          <xs:attribute type="xs:byte" name="certificatePercentage" use="optional"/>
          <xs:attribute type="xs:string" name="certificatePresident" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Benefits">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Benefit" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FreeCertificate">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:short" name="corporationId" use="optional"/>
          <xs:attribute type="xs:byte" name="percentage" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Certificate"/>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="row" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Private">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Benefits" minOccurs="0"/>
        <xs:element ref="Certificate"/>
      </xs:sequence>
      <xs:attribute type="xs:short" name="id" use="required"/>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="abbrev" use="required"/>
      <xs:attribute type="xs:short" name="cost" use="optional"/>
      <xs:attribute type="xs:string" name="note" use="optional"/>
      <xs:attribute type="xs:byte" name="revenue" use="optional"/>
      <xs:attribute type="xs:string" name="homeCell1" use="required"/>
      <xs:attribute type="xs:byte" name="homeLocation1" use="required"/>
      <xs:attribute type="xs:byte" name="homeLocation2" use="optional"/>
      <xs:attribute type="xs:string" name="special" use="optional"/>
      <xs:attribute type="xs:string" name="mustSell" use="optional"/>
      <xs:attribute type="xs:short" name="exchangeID" use="optional"/>
      <xs:attribute type="xs:byte" name="exchangePercentage" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Share">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Certificate" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:short" name="id" use="required"/>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="abbrev" use="required"/>
      <xs:attribute type="xs:string" name="homeCell1" use="required"/>
      <xs:attribute type="xs:byte" name="homeLocation1" use="required"/>
      <xs:attribute type="xs:string" name="homeCell2" use="optional"/>
      <xs:attribute type="xs:byte" name="homeLocation2" use="optional"/>
      <xs:attribute type="xs:string" name="bgColor" use="required"/>
      <xs:attribute type="xs:string" name="fgColor" use="required"/>
      <xs:attribute type="xs:byte" name="tokens" use="required"/>
      <xs:attribute type="xs:short" name="closeOnTrainPurchase" use="optional"/>
      <xs:attribute type="xs:string" name="mustBuyTrain" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="StartPacket">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Item" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Corporations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Private" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="Share" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="StartPacket"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Krazick/Krazick.github.io/18XX-Game-Engine-XML/XML/1853/1853-Companies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<Corporations
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://krazick.github.io/schema 
						https://krazick.github.io/18XX-Game-Engine-XML/public/XSD/18XX-Corporations.xsd">
	<Share id="1901" name="East Indian Railway" abbrev="EIR" tileLaysAllowed="2" actorBank="Corporate Bank"
		homeCell1="Jab" homeLocation1="7" homeCell2="Hx" homeLocation2="10" homeType="both"
		bgColor="Red" fgColor="White" tokens="5" tokenType="FixedCost" startPrice="0,14">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1902" name="Great Indian Pennisula Railway" abbrev="GIP" tileLaysAllowed="2" actorBank="Corporate Bank"
		homeCell1="Mi" homeLocation1="10" homeCell2="Ht" homeLocation2="10" homeType="both"
		bgColor="204,102,0" fgColor="White" tokens="5" tokenType="FixedCost" startPrice="1,13">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1903" name="North Western Railway" abbrev="NWR" tileLaysAllowed="2" actorBank="Corporate Bank"
		homeCell1="Fn" homeLocation1="7" homeCell2="Ck" homeLocation2="11" homeType="both"
		bgColor="Black" fgColor="White" tokens="5" tokenType="FixedCost" startPrice="2,12">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1904" name="Bengal Nagpur Railway" abbrev="BNR" tileLaysAllowed="2" actorBank="Corporate Bank"
		homeCell1="Kq" homeLocation1="17" homeCell2="Jab" homeLocation2="11" homeType="both"
		bgColor="Dark Green" fgColor="White" tokens="5" tokenType="FixedCost" startPrice="3,11">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1905" name="Bombay, Baroda and Central India Railway" actorBank="Corporate Bank"
		abbrev="BBCI" homeCell1="Hj" homeLocation1="15" bgColor="Deep Blue"
		fgColor="White" tokens="4" tokenType="FixedCost" startPrice="4,10">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1906" name="Madras and South Mahratta Railway" abbrev="MSM" actorBank="Corporate Bank"
		homeCell1="Rr" homeLocation1="7" bgColor="153,0,204" fgColor="Black"
		tokens="4" tokenType="FixedCost" startPrice="5,9">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1907" name="South Indian Railway" abbrev="SIR" actorBank="Corporate Bank"
		homeCell1="Tp" homeLocation1="16" bgColor="Yellow" fgColor="Black"
		tokens="4" tokenType="FixedCost" startPrice="6,8">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1908" name="Bengal Assam Railway" abbrev="BAR" actorBank="Corporate Bank"
		homeCell1="Jah" homeLocation1="12" bgColor="Light Blue" fgColor="Black"
		tokens="3" tokenType="FixedCost" startPrice="7,7">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
</Corporations>
