=== Krazick/Krazick.github.io/18XX-Game-Engine-XML/public/XSD/18XX-Cities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" 
	elementFormDefault="qualified" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CityInfo">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:byte" name="id" use="required"/>
          <xs:attribute type="xs:string" name="name" use="optional"/>
          <xs:attribute type="xs:byte" name="type" use="required"/>
          <xs:attribute type="xs:byte" name="location" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cities">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="CityInfo" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Krazick/Krazick.github.io/18XX-Game-Engine-XML/XML/1853/1853-Cities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<Cities 
	xmlns="https://krazick.github.io/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://krazick.github.io/18XX-Game-Engine-XML/public/XSD/18XX-Cities.xsd
						https://krazick.github.io/schema">
	<!-- Need to add a 'bond="##"' value
		The value of the Bond is the minimum scoring value of all the cities named in the bid. 
		This is €50 for Calcutta, £40 for Bombay and Delhi, £30 for Madras and £20 for all other cities.
						-->
	<CityInfo id="1" name="Karachi" type="3" bond="20" shareCompanies="1903" />
	<CityInfo id="2" name="Bombay" type="3" bond="40" shareCompanies="1902,1905" />
	<CityInfo id="3" name="Multan" type="3" bond="20" shareCompanies="1903" />
	<CityInfo id="4" name="Ahmadabad" type="3" bond="20" shareCompanies="1905" />
	<CityInfo id="5" location="14" name="Peshawar" type="3" bond="20" shareCompanies="1903" />
	<CityInfo id="6" location="14" name="Rawalpindi" type="3" bond="20" shareCompanies="1903" />
	<CityInfo id="7" location="7" name="Lahore" type="3" bond="20" shareCompanies="1903" />
	<CityInfo id="8" name="Delhi" type="3" bond="40" shareCompanies="1901,1902,1903,1905" />
	<CityInfo id="9" location="7" name="Jaipur" type="3" bond="20" shareCompanies="1905" />
	<CityInfo id="10" location="7" name="Ajmer" type="3" bond="20" shareCompanies="1905" />
	<CityInfo id="11" name="Cawnpore" type="3" bond="20" shareCompanies="1902" />
	<CityInfo id="12" name="Lucknow" type="3" bond="20" shareCompanies="1901" />
	<CityInfo id="13" name="Allahabad" type="3" bond="20" shareCompanies="1902" />
	<CityInfo id="14" location="17" name="Benares" type="4" bond="20" shareCompanies="1901" />
	<CityInfo id="15" location="14" name="Patna" type="3" bond="20" shareCompanies="1901" />
	<CityInfo id="16" name="Nagpur" type="3" bond="20" shareCompanies="1904" />
	<CityInfo id="17" location="14" name="Hyderbad" type="3" bond="20" shareCompanies="1904,1906" />
	<CityInfo id="18" name="Mysore" type="3" bond="20" shareCompanies="1907" />
	<CityInfo id="19" location="17" name="Bangalore" type="3" bond="20" shareCompanies="1906" />
	<CityInfo id="20" name="Madras" type="3" bond="30" shareCompanies="1906,1907"/>
	<CityInfo id="21" location="14" name="Trichniopoly" type="4" bond="20" shareCompanies="1907"/>
	<CityInfo id="22" name="Calcutta" type="3" bond="50" shareCompanies="1,4,8" />
	<CityInfo id="23" location="14" name="Dacca" type="3" bond="20" shareCompanies="1908" />
	<CityInfo id="24" location="14" name="Chittagong" type="3" bond="20" shareCompanies="1908" />
</Cities>
